# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_DATA_HOST)%/' }
    indexes:
        inverters_data:
            properties:
                id:
                    type: keyword
                projectId:
                    type: keyword
                datetime:
                    type: date
                inverterId:
                    type: keyword
                pac:
                    type: integer
                pacConsolidate:
                    type: integer
            persistence:
                driver: orm
                model: App\Entity\InvertersData
