# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_DATA_HOST)%' }
    indexes:
        inverters_data:
            properties:
                id: ~
                projectId: ~
                datetime:
                    type: date
                inverterId: ~
                pac: ~
                pacConsolidate: ~
            persistence:
                driver: orm
                model: App\Entity\InvertersData
