version: '3.7'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        environment:
            discovery.type: "single-node"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.0
        ports:
            - 5601:5601
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elastic
        depends_on:
            - elasticsearch
    database:
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306'
        volumes:
            - ./docker/mysql/dump:/docker-entrypoint-initdb.d
            - database:/var/lib/mysql
    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        ports:
            - '5672:5672'
            - '8080:15672'
volumes:
    database: {}
    elasticsearch_data:
        driver: local

networks:
    elastic:
        driver: bridge
